# Generated by Django 5.0.7 on 2024-08-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='km',
            field=models.IntegerField(null=True),
        ),
    ]
