# Generated by Django 5.0.7 on 2024-08-01 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_brand_options_alter_car_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='cylinders',
            field=models.IntegerField(null=True, verbose_name='Cilindros'),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Precio en dolares'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marca', to='cars.brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='cars.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.IntegerField(verbose_name='Cantidad de Puertas'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combustible', to='cars.fuel', verbose_name='Combustible'),
        ),
        migrations.AlterField(
            model_name='car',
            name='km',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de Kilometros'),
        ),
        migrations.AlterField(
            model_name='car',
            name='nameplate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelo', to='cars.nameplate', verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='car',
            name='traction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traccion', to='cars.traction', verbose_name='Tracción'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmision', to='cars.transmission', verbose_name='Transmisión'),
        ),
        migrations.AlterField(
            model_name='car',
            name='used',
            field=models.BooleanField(verbose_name='Usado'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='nameplate',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='traction',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='car',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pais', to='cars.country', verbose_name='País'),
        ),
    ]
