# Generated by Django 5.0.7 on 2024-08-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_sold_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cylinders',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Cilindros'),
        ),
    ]
