# Generated by Django 5.0.7 on 2024-08-05 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_car_cylinders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='thumbnails/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='carimage',
            options={'verbose_name': 'Imagen', 'verbose_name_plural': 'Imagenes'},
        ),
        migrations.AlterField(
            model_name='carimage',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Auto', to='cars.car', verbose_name='Autos'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(null=True, upload_to='car_images/'),
        ),
        migrations.AddField(
            model_name='car',
            name='thumbnail',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='transmision', to='cars.thumbnail', verbose_name='Transmisión'),
        ),
        migrations.DeleteModel(
            name='PriceHistory',
        ),
    ]
