# Generated by Django 5.0.7 on 2024-08-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_thumbnail_alter_carimage_options_alter_carimage_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails/'),
        ),
        migrations.DeleteModel(
            name='Thumbnail',
        ),
    ]
