# Generated by Django 5.0.7 on 2024-08-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_car_thumbnail_delete_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails/', verbose_name='thumbnail'),
        ),
    ]
