# Generated by Django 5.0.7 on 2024-08-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_alter_car_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_edit',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='date_edit',
            field=models.DateField(null=True),
        ),
    ]
