# Generated by Django 5.0.7 on 2024-08-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_comment_date_edit_review_date_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
