# Generated by Django 5.0.7 on 2024-08-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_comment_time_alter_comment_date_alter_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time_edit',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
