# Generated by Django 5.0.7 on 2024-08-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_comment_time_edit_review_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='time_edit',
            field=models.TimeField(null=True),
        ),
    ]
